# @package _global_
defaults:
  - /algo_base@algo: motrix.fastsac
  - /sonic_model@algo.sonic.model: lafan
  - _self_
task:
  env: g1-sonic-lafan
  rllib: motrix
  algo: fastsac
num_envs: 1024
play_num_envs: 16
seed: 1
checkpoint:
  interval: 1000
algo:
  sonic:
    enabled: true
    profile: lafan
  trainer:
    num_learning_iterations: 40000
