# @package algo.sonic.model
# Intermediate LAFAN SONIC temporal/profile size.
num_future_frames: 4
num_tokens: 2
token_dim: 8
fsq_levels: 32
action_dim: 29
actor_hidden_dim: 256
critic_hidden_dim: 256
g1_encoder_hidden_dims: [512, 256]
smpl_encoder_hidden_dims: [512, 256]
g1_motion_decoder_hidden_dims: [512, 256]
g1_control_decoder_hidden_dims: [1024, 512]
