defaults:
  - _self_
  - task: null
  - override hydra/job_logging: stdout

hydra:
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: ${hydra.job.num}
  job:
    chdir: false

artifact: ???
runtime: ???
duration_s: null
command: null
